name: glamori
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6

  extended_image: ^8.2.0
  carousel_slider: ^4.0.0
  flutter_svg: ^2.0.9
  flutter_pin_code_fields: ^2.2.0
  qr_flutter: ^4.1.0
  intl: ^0.17.0
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.5
  fluttertoast: ^8.2.4
  dio: ^5.4.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0
  image_cropper: ^5.0.1
  firebase_core: ^2.25.0
  firebase_messaging: ^14.7.11
  flutter_local_notifications: ^16.3.2
  youtube_player_flutter: ^8.1.2
  flutter_markdown: ^0.6.20

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoApp.png"
  min_sdk_android: 21
  icon_size: 238
  web:
    generate: true
    image_path: "assets/images/logoApp.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
    icon_size: 108
  windows:
    generate: true
    image_path: "assets/images/logoApp.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logoApp.png"

dev_dependencies:
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Sathoshi
      fonts:
        - asset: fonts/Satoshi-Regular.ttf
        - asset: fonts/Satoshi-Bold.ttf

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/lotties/

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
      ios:

  flavors:
    app_release:
      app:
        name: "Glamori"
      android:
        applicationId: "com.evetech.glamori"
      ios:
        bundleId: "com.evetech.glamori"

    app_staging:
      app:
        name: "Glamori"
      android:
        applicationId: "com.evetech.glamori.staging"
      ios:
        bundleId: "com.evetech.glamori.staging"
