// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIyWQUJrL4Oy7AGRQYM3Aw8OK0UFkdlhE',
    appId: '1:168288289012:web:89e5933286fcb714911ea1',
    messagingSenderId: '168288289012',
    projectId: 'glamori-6cb6f',
    authDomain: 'glamori-6cb6f.firebaseapp.com',
    storageBucket: 'glamori-6cb6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjTFGmeRpaS4K10xy8BNhANr8F4AItzcA',
    appId: '1:168288289012:android:428890ec5d4af778911ea1',
    messagingSenderId: '168288289012',
    projectId: 'glamori-6cb6f',
    storageBucket: 'glamori-6cb6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBViaa0oPj4uNOo3agAGPYMaCmxXAjredc',
    appId: '1:168288289012:ios:a66d4a51a40e2070911ea1',
    messagingSenderId: '168288289012',
    projectId: 'glamori-6cb6f',
    storageBucket: 'glamori-6cb6f.appspot.com',
    iosBundleId: 'com.evetech.glamori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBViaa0oPj4uNOo3agAGPYMaCmxXAjredc',
    appId: '1:168288289012:ios:6aec6d0db50ad1fe911ea1',
    messagingSenderId: '168288289012',
    projectId: 'glamori-6cb6f',
    storageBucket: 'glamori-6cb6f.appspot.com',
    iosBundleId: 'com.evetech.glamori.glamori.RunnerTests',
  );
}
